
version: 2

models:
    - name: modeled_users_with_product_usage.sql
      description: "Users modeled with product usage data"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_form_signups.sql
      description: "Inbound form signups found on landing page, blog posts, social posts, ad campaigns, etc."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: all_users
      description: "CUSTOMER 360. All users in available in the data warehouse. Pulling data from Sales, Marketing, Support, and Product."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: all_events
      description: "Events captured on client product and server-side applications"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_at_risk_customers.sql
      description: "At risk customers - used to target customers for re-engagement"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_available_catalog.sql
      description: "Catalog of available content"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_client_side_events.sql
      description: "Events captured on client-side"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_high_LTV_customers.sql
      description: "High LTV Customers"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_server_side_events.sql
      description: "Events on server-side"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
