version: 2

models:
  - name: patxu_testing
    description: "Events captured on client product and server-side applications"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
