
version: 2

models:
    - name: modeled_users_with_lead_scores.sql
      description: "Users modeled with lead score data"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_users_with_product_usage.sql
      description: "Users modeled with product usage data"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_form_signups.sql
      description: "Inbound form signups found on landing page, blog posts, social posts, ad campaigns, etc."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: all_users
      description: "CUSTOMER 360 data. All users in available in the data warehouse. Pulling data from Sales, Marketing, Support, and Product."
      columns:
          - name: USER_ID
            description: "The external user ID of the user"
          - name: ACTIVE_POC
            description: "Whether or not the user is in a POC (true/false)"
          - name: AD_CONVERSION
            description: "Whether or not the user converted from an ad (true/false)"
          - name: DASHBOARD_VIEWS
            description: "How many times the user has viewed a dashboard"
          - name: EMAIL
            description: "The user's primary email"
          - name: ENGAGEMENT_LAST_7_DAYS
            description: "Engagement score 1-100 from data eng team"
          - name: FAVORITE_BRAND
            description: "The user's favorite brand based on purchase history"
          - name: FIRST_NAME
            description: "The user's first name"
          - name: LAST_NAME
            description: "The user's last name"
          - name: LEAD_GRADE
            description: "A grade for the user's health as a lead 1-100"
          - name: LEAD_SCORE
            description: "A cumulative score for lead behavior based on actions in-app"
          - name: NUM_BLOG_POSTS_VIEWED
            description: "How many blog posts the user viewed"
          - name: PAGEVIEWS
            description: "Total number of pageviews the user triggered"
          - name: SIGN_UP_DATE
            description: "Date the user signed up on"
          - name: TRIAL_USER
            description: "Whether or not the user is in a trial (true/false)"
          - name: VIP_CUSTOMER
            description: "Whether or not the user is a VIP customer (true/false)"
    - name: all_events
      description: "Events captured on client product and server-side applications"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_at_risk_customers.sql
      description: "At risk customers - used to target customers for re-engagement"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_available_catalog.sql
      description: "Catalog of available content"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_client_side_events.sql
      description: "Events captured on client-side"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_high_LTV_customers.sql
      description: "High LTV Customers"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: modeled_server_side_events.sql
      description: "Events on server-side"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
